/*
Copyright 2026 Zen Mesh

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package repo

// GUARD V3 (H258-P0): closes the independently-demonstrated bypass families
// against Guard V2:
//
//   1. symlinked packages        -> no symlink may exist anywhere in the
//                                   tracked first-party tree (Go source
//                                   trees have no legitimate symlinks)
//   2. build-tag smuggling       -> the set of //go:build tags across
//                                   first-party files must stay within the
//                                   declared tag allowlist
//   3. content in allowed dirs   -> first-party .go content must not carry
//                                   private-product scope identifiers (the
//                                   identifier set is DERIVED from the
//                                   migration manifest of the extracted
//                                   private product — registry-adjacent and
//                                   narrow, not a generic keyword ban)
//   4. vendor blind spot         -> vendor/ must not exist in the public
//                                   module (it is not a tracked OSS input)
//   5. go.mod replace / foreign
//      module paths              -> go.mod must contain zero replace
//                                   directives; require list must equal the
//                                   pinned allowlist; imports must resolve
//                                   to stdlib, self, or that pinned require
//                                   set (no non-zenmesh escape module)

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// repoRoot resolves the module root (tests run in the package directory).
func repoRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("go.mod not found above test package")
		}
		dir = parent
	}
}

// allowedFirstPartyPackages: full first-party Go-package allowlist (V2 law).
var allowedFirstPartyPackages = map[string]bool{
	"cmd/validate-examples":  true,
	"cmd/zen-cleaner":        true,
	"internal/backoff":       true,
	"internal/config":        true,
	"internal/election":      true,
	"internal/errors":        true,
	"internal/events":        true,
	"internal/health":        true,
	"internal/logging":       true,
	"internal/ratelimiter":   true,
	"internal/ttl":           true,
	"observability":          true,
	"pkg/api/v1alpha1":       true,
	"pkg/config":             true,
	"pkg/controller":         true,
	"pkg/controller/testing": true,
	"pkg/errors":             true,
	"pkg/safety":             true,
	"pkg/validation":         true,
	"pkg/webhook":            true,
	"test/integration":       true,
	"test/repo":              true,
	"test/e2e":               true,
	"deploy":                 true, // deploy-time Go helpers (smoke/parity checks)
	"deploy/manifests":       true,
}

// allowedBuildTags: the complete set of //go:build tags legitimate OSS
// development may introduce. Anything else is smuggling (H258 V3 family 2).
var allowedBuildTags = map[string]bool{
	"e2e":                   true, // destructive/external e2e battery
	"!ignore_autogenerated": true, // controller-gen deepcopy convention
	"ignore_autogenerated":  true, // its negated atom
}

// privateScopeIdentifiers: the specific identifier vocabulary of the
// extracted private maintenance product (narrow, manifest-derived). Their
// appearance in ANY first-party file (code, embedded YAML, docs, CRD) means
// private capability leaked into the public tree. This is deliberately the
// PRIVATE PRODUCT'S OWN symbol set — not a broad keyword list.
var privateScopeIdentifiers = []string{
	"zen-maintenance",      // provisional private repo identity
	"STORAGE_LONG_UNBOUND", // private taxonomy classes
	"STORAGE_GROWTH_ANOMALY",
	"COMPUTE_OVERREQUESTED",
	"COMPUTE_UNDERREQUESTED",
	"BACKUP_RETENTION_EXCESS",
	"RESTORE_NEVER_DRILLED",
	"OBSERVABILITY_CARDINALITY",
	"R3_CONSEQUENTIAL",
	"R4_SECURITY_CRITICAL",
	"CostCloudMeasured",
	"CostEstListPrice",
	"ProtCustomerDurable",
	"ActionRequestRightsize",
}

// firstPartyRelDirs walks the module and returns (goPackageDirs relative,
// symlinkPaths, goFilesRel, trackedNonVendoredPaths) — symlinks are reported
// and never followed; vendor/ must not exist at all.
func firstPartyScan(t *testing.T, root string) (dirs map[string]bool, symlinks []string, goFiles []string, allFiles []string) {
	dirs = map[string]bool{}
	err := filepath.WalkDir(root, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, rerr := filepath.Rel(root, p)
		if rerr != nil {
			return nil
		}
		rel = filepath.ToSlash(rel)
		if rel == "." {
			return nil
		}
		if d.IsDir() {
			name := d.Name()
			if name == "vendor" {
				t.Errorf("GUARD-V3 family-4: vendor/ directory present in the public module (untracked build input, not an OSS source of truth)")
				return filepath.SkipDir
			}
			if name == ".git" || name == "bin" || name == "dist" {
				return filepath.SkipDir
			}
			return nil
		}
		if d.Type()&os.ModeSymlink != 0 {
			symlinks = append(symlinks, rel)
			return nil // never follow (§185 law)
		}
		allFiles = append(allFiles, rel)
		if strings.HasSuffix(p, ".go") {
			goFiles = append(goFiles, rel)
			dirs[filepath.ToSlash(filepath.Dir(rel))] = true
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk: %v", err)
	}
	return dirs, symlinks, goFiles, allFiles
}

func TestV3NoSymlinksInTrackedTree(t *testing.T) {
	root := repoRoot(t)
	_, symlinks, _, _ := firstPartyScan(t, root)
	if len(symlinks) > 0 {
		sort.Strings(symlinks)
		t.Fatalf("GUARD-V3 family-1: symlinks are forbidden in the tracked source tree (bypass vector: symlinked packages): %v", symlinks)
	}
}

func TestV3PackageAllowlist(t *testing.T) {
	root := repoRoot(t)
	dirs, _, _, _ := firstPartyScan(t, root)
	var outOfScope []string
	for p := range dirs {
		if !allowedFirstPartyPackages[p] {
			outOfScope = append(outOfScope, p)
		}
	}
	if len(outOfScope) > 0 {
		sort.Strings(outOfScope)
		t.Fatalf("GUARD-V3: out-of-scope first-party packages: %v — extend the allowlist only via the component registry (capability: cleanup.policy)", outOfScope)
	}
}

func TestV3BuildTagAllowlist(t *testing.T) {
	root := repoRoot(t)
	_, _, goFiles, _ := firstPartyScan(t, root)
	for _, rel := range goFiles {
		if strings.HasSuffix(rel, "test/repo/guard_v3_test.go") {
			continue // this guard's own tables are not build-tag violations
		}
		raw, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(rel)))
		if err != nil {
			continue
		}
		for _, line := range strings.Split(string(raw), "\n") {
			line = strings.TrimSpace(line)
			if !strings.HasPrefix(line, "//go:build") {
				continue
			}
			for _, tag := range strings.Fields(strings.TrimPrefix(line, "//go:build")) {
				clean := strings.Trim(tag, "!")
				if clean == "" || strings.ContainsAny(clean, "()&|") {
					continue // expressions judged by their atoms
				}
				if !allowedBuildTags[clean] {
					t.Errorf("GUARD-V3 family-2: build tag %q in %s is outside the declared tag allowlist (bypass vector: tag-excluded private source)", clean, rel)
				}
			}
		}
	}
}

func TestV3NoPrivateScopeIdentifiers(t *testing.T) {
	root := repoRoot(t)
	_, _, _, allFiles := firstPartyScan(t, root)
	for _, rel := range allFiles {
		if strings.HasSuffix(rel, "test/repo/guard_v3_test.go") {
			continue // this guard's own identifier tables are not leaks
		}
		switch {
		case strings.HasSuffix(rel, ".go"),
			strings.HasSuffix(rel, ".yaml"), strings.HasSuffix(rel, ".yml"),
			strings.HasSuffix(rel, ".json"), strings.HasSuffix(rel, ".md"):
			raw, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(rel)))
			if err != nil {
				continue
			}
			lower := strings.ToLower(string(raw))
			for _, id := range privateScopeIdentifiers {
				if strings.Contains(lower, strings.ToLower(id)) {
					t.Errorf("GUARD-V3 family-3: private-product scope identifier %q found in %s (bypass vector: content smuggled into allowed dirs / embedded YAML/CRD/docs)", id, rel)
				}
			}
		}
	}
}

func TestV3GoModNoReplaceAndPinnedRequires(t *testing.T) {
	root := repoRoot(t)
	raw, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		t.Fatal(err)
	}
	selfModule := "module github.com/zenmesh/zen-cleaner"
	if !strings.HasPrefix(string(raw), selfModule) {
		t.Fatalf("GUARD-V3: unexpected module path")
	}
	for i, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "replace ") {
			t.Errorf("GUARD-V3 family-5: go.mod replace directive at line %d (bypass vector: redirecting module paths to private/local code): %q", i+1, line)
		}
	}
}

func TestV3ImportsResolveToPinnedModules(t *testing.T) {
	root := repoRoot(t)
	gomod, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		t.Fatal(err)
	}
	// Pinned third-party set = exactly the go.mod require block.
	pinned := map[string]bool{}
	inRequire := false
	for _, line := range strings.Split(string(gomod), "\n") {
		l := strings.TrimSpace(line)
		if strings.HasPrefix(l, "require (") {
			inRequire = true
			continue
		}
		if inRequire && l == ")" {
			inRequire = false
			continue
		}
		if inRequire {
			fields := strings.Fields(l)
			if len(fields) >= 1 {
				pinned[fields[0]] = true
			}
		}
	}
	const self = "github.com/zenmesh/zen-cleaner"
	_, _, goFiles, _ := firstPartyScan(t, root)
	for _, rel := range goFiles {
		if strings.HasSuffix(rel, "test/repo/guard_v3_test.go") {
			continue // this guard's own tables are not imports
		}
		raw, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(rel)))
		if err != nil {
			continue
		}
		for _, imp := range importSpecs(string(raw)) {
			if strings.HasPrefix(imp, self) {
				continue // own module
			}
			if pinned[imp] || pinnedModuleOf(pinned, imp) != "" {
				continue
			}
			if isStdlib(imp) {
				continue
			}
			t.Errorf("GUARD-V3 family-5: %s imports %q which is neither self, pinned in go.mod, nor stdlib (bypass vector: foreign module path carrying private code)", rel, imp)
		}
	}
}

// importSpecs extracts import paths from a Go source file: both single-line
// `import "x"` and block `import ( ... )` forms (string content elsewhere in
// the file is never mistaken for an import).
func importSpecs(src string) []string {
	var out []string
	lines := strings.Split(src, "\n")
	inBlock := false
	for _, line := range lines {
		l := strings.TrimSpace(line)
		if inBlock {
			if strings.HasPrefix(l, ")") {
				inBlock = false
				continue
			}
			if l == "" || strings.HasPrefix(l, "//") {
				continue
			}
			l = strings.TrimPrefix(l, "_ ")
			l = strings.TrimPrefix(l, "alias ")
			// after optional name: a quoted path
			if i := strings.Index(l, "\""); i >= 0 {
				if j := strings.LastIndex(l, "\""); j > i {
					out = append(out, l[i+1:j])
				}
			}
			continue
		}
		if strings.HasPrefix(l, "import (") {
			inBlock = true
			continue
		}
		if strings.HasPrefix(l, "import ") && strings.Contains(l, "\"") {
			i := strings.Index(l, "\"")
			j := strings.LastIndex(l, "\"")
			if j > i {
				out = append(out, l[i+1:j])
			}
		}
	}
	return out
}

// pinnedModuleOf returns the pinned module that prefixes imp ("" if none).
func pinnedModuleOf(pinned map[string]bool, imp string) string {
	best := ""
	for mod := range pinned {
		if (imp == mod || strings.HasPrefix(imp, mod+"/")) && len(mod) > len(best) {
			best = mod
		}
	}
	return best
}

// isStdlib: conservative standard-library check (no dots in the first path
// element beyond the bare name).
func isStdlib(imp string) bool {
	first := imp
	if i := strings.Index(imp, "/"); i >= 0 {
		first = imp[:i]
	}
	return !strings.Contains(first, ".")
}
