/*
Copyright 2026 Zen Mesh

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package repo

// GUARD V4 (Support2 S171 INDEPENDENT_FAIL closeout).
//
// Threat model (§3): prevent ACCIDENTAL private-capability leakage, forbidden
// dependencies and forbidden build inputs. It cannot recognize fully
// renamed/rewritten algorithms — that residual is documented, not claimed.
//
// Layers (each backed by Go tooling, not fragile regex):
//
//   L1 package allowlist      — normalized comparison (V3B-6)
//   L2 AST import guard       — go/parser: alias/blank/dot/grouped/
//                               single-line/build-tag-excluded files all
//                               parsed (V3B-7)
//   L3 build-constraint guard — go/build/constraint legal parse of
//                               //go:build AND legacy // +build, AND/OR/NOT,
//                               parentheses; atom allowlist (V3B-1/V3B-2)
//   L4 private-scope markers  — normalized identifier matching (V3B-8)
//   L5 module law             — no replace, no go.work, no nested go.mod,
//                               pinned requires
//   L6 tree law               — no symlinks, no vendor/

import (
	"fmt"
	"go/build/constraint"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"golang.org/x/mod/modfile"
)

// normalizeIdent: lowercase and strip _/- separators — marker/allowlist
// matching is done on the normalized form (V3B-6/V3B-8).
func normalizeIdent(s string) string {
	s = strings.ToLower(s)
	s = strings.ReplaceAll(s, "_", "")
	s = strings.ReplaceAll(s, "-", "")
	s = strings.ReplaceAll(s, ".", "")
	return s
}

// allowedFirstPartyPackages is the normalized first-party allowlist.
var allowedFirstPartyPackages = map[string]bool{}

func init() {
	for _, p := range []string{
		"cmd/validate-examples", "cmd/zen-cleaner",
		"internal/backoff", "internal/config", "internal/election",
		"internal/errors", "internal/events", "internal/health",
		"internal/logging", "internal/ratelimiter", "internal/ttl",
		"observability",
		"pkg/api/v1alpha1", "pkg/config", "pkg/controller",
		"pkg/controller/testing", "pkg/errors", "pkg/safety",
		"pkg/validation", "pkg/webhook",
		"test/integration", "test/repo", "test/e2e",
		"deploy", "deploy/manifests",
	} {
		allowedFirstPartyPackages[normalizeIdent(p)] = true
	}
}

// allowedBuildTagAtoms: every build-constraint atom must be here (V3 legal
// parse; both //go:build and // +build syntax).
var allowedBuildTagAtoms = map[string]bool{
	"e2e":                  true,
	"ignoreautogenerated": true, // normalized form (source tag: ignore_autogenerated)
}

// privateScopeMarkers: the private product's own identifiers, matched on
// normalized form (V3B-8: zen_Maintenance / zenmaintenance / ZEN-MAINTENANCE
// all normalize to the same needle).
var privateScopeMarkers = []string{
	"zenmaintenance",
	"storagelongunbound", "storagegrowthanomaly",
	"computeoverrequested", "computeunderrequested",
	"backupretentionexcess", "restoreneverdrilled",
	"observabilitycardinality",
	"r3consequential", "r4securitycritical",
	"costcloudmeasured", "costestlistprice",
	"protcustomerdurable", "actionrequestrightsi ze",
}

// v4File is one scanned first-party Go file.
type v4File struct {
	rel      string
	imports  []string // AST-resolved import paths (all forms)
	tagAtoms []string // constraint atoms (normalized)
	parseErr error
}

func repoRootV4(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("go.mod not found")
		}
		dir = parent
	}
}

// scanV4 walks the module: symlinks reported (L6), vendor reported (L6),
// nested go.mod reported (L5), and every .go file parsed for imports (L2)
// and build constraints (L3).
func scanV4(t *testing.T, root string) (dirs map[string]bool, files []v4File, violations []string) {
	dirs = map[string]bool{}
	fset := token.NewFileSet()
	err := filepath.WalkDir(root, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, rerr := filepath.Rel(root, p)
		if rerr != nil {
			return nil
		}
		rel = filepath.ToSlash(rel)
		if rel == "." {
			return nil
		}
		if d.IsDir() {
			switch d.Name() {
			case "vendor":
				violations = append(violations, "L6: vendor/ present in public module")
				return filepath.SkipDir
			case ".git", "bin", "dist", "node_modules":
				// §6: bin/dist are build OUTPUTS — nothing Go-buildable may
				// hide there and enter the module build.
				return filepath.SkipDir
			}
			return nil
		}
		if d.Type()&os.ModeSymlink != 0 {
			violations = append(violations, "L6: symlink in tracked tree: "+rel)
			return nil
		}
		if d.Name() == "go.mod" && rel != "go.mod" {
			violations = append(violations, "L5: nested module go.mod at "+rel)
			return nil
		}
		if !strings.HasSuffix(p, ".go") {
			return nil
		}
		f := v4File{rel: rel}
		af, err := parser.ParseFile(fset, p, nil, parser.ImportsOnly|parser.ParseComments)
		if err != nil {
			f.parseErr = err
		} else {
			for _, imp := range af.Imports {
				path := strings.Trim(imp.Path.Value, `"`)
				f.imports = append(f.imports, path)
			}
		}
		// L3: legal build-constraint parse (both syntaxes).
		raw, _ := os.ReadFile(p)
		for _, line := range strings.Split(string(raw), "\n") {
			tl := strings.TrimSpace(line)
			if !strings.HasPrefix(tl, "//") {
				continue
			}
			if strings.HasPrefix(tl, "//go:build") || strings.HasPrefix(tl, "// +build") || strings.HasPrefix(tl, "//+build") {
				expr, perr := constraint.Parse(tl)
				if perr != nil {
					violations = append(violations, fmt.Sprintf("L3: %s: unparseable build constraint %q (%v)", rel, tl, perr))
					continue
				}
				f.tagAtoms = append(f.tagAtoms, constraintAtoms(expr)...)
			}
		}
		files = append(files, f)
		dirs[filepath.ToSlash(filepath.Dir(rel))] = true
		return nil
	})
	if err != nil {
		t.Fatalf("walk: %v", err)
	}
	return dirs, files, violations
}

// constraintAtoms walks the parsed constraint expression collecting tag
// atoms (TagExpr/NotExpr/AndExpr/OrExpr per go/build/constraint AST).
func constraintAtoms(expr constraint.Expr) []string {
	var out []string
	switch e := expr.(type) {
	case *constraint.TagExpr:
		out = append(out, normalizeIdent(e.Tag))
	case *constraint.NotExpr:
		out = append(out, constraintAtoms(e.X)...)
	case *constraint.AndExpr:
		out = append(out, constraintAtoms(e.X)...)
		out = append(out, constraintAtoms(e.Y)...)
	case *constraint.OrExpr:
		out = append(out, constraintAtoms(e.X)...)
		out = append(out, constraintAtoms(e.Y)...)
	}
	return out
}

// TestV4 is the single aggregated guard battery (L1-L6).
func TestV4(t *testing.T) {
	root := repoRootV4(t)
	dirs, files, violations := scanV4(t, root)

	// L1: package allowlist (normalized).
	var outOfScope []string
	for p := range dirs {
		if !allowedFirstPartyPackages[normalizeIdent(p)] {
			outOfScope = append(outOfScope, p)
		}
	}
	if len(outOfScope) > 0 {
		sort.Strings(outOfScope)
		violations = append(violations, fmt.Sprintf("L1: out-of-scope first-party packages: %v", outOfScope))
	}

	// L2: imports via AST (all forms), resolved to pinned modules.
	gomodRaw, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		t.Fatal(err)
	}
	mf, err := modfile.Parse("go.mod", gomodRaw, nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(mf.Replace) > 0 {
		violations = append(violations, "L5: go.mod contains replace directives")
	}
	pinned := map[string]bool{}
	for _, r := range mf.Require {
		pinned[r.Mod.Path] = true
	}
	const self = "github.com/zenmesh/zen-cleaner"
	for _, f := range files {
		if f.parseErr != nil {
			violations = append(violations, "L2: unparsable Go file "+f.rel+": "+f.parseErr.Error())
			continue
		}
		if strings.HasSuffix(f.rel, "test/repo/guard_v4_test.go") {
			continue
		}
		for _, imp := range f.imports {
			if imp == self || strings.HasPrefix(imp, self+"/") {
				continue
			}
			if pinned[imp] || pinnedPrefix(pinned, imp) != "" {
				continue
			}
			if isStdlibV4(imp) {
				continue
			}
			violations = append(violations, fmt.Sprintf("L2: %s imports %q — not self/pinned/stdlib", f.rel, imp))
		}
	}

	// L3: build-tag atoms within the declared set.
	for _, f := range files {
		for _, a := range f.tagAtoms {
			if !allowedBuildTagAtoms[a] {
				violations = append(violations, fmt.Sprintf("L3: %s: build-constraint atom %q outside declared set", f.rel, a))
			}
		}
	}

	// L4: private-scope markers in ANY tracked text file (normalized).
	for _, rel := range trackedTextFiles(t, root) {
		raw, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(rel)))
		if err != nil {
			continue
		}
		hay := normalizeIdent(string(raw))
		for _, marker := range privateScopeMarkers {
			if strings.Contains(hay, normalizeIdent(marker)) {
				violations = append(violations, fmt.Sprintf("L4: private-scope marker %q in %s", marker, rel))
			}
		}
	}

	// L6 violations were appended during the walk.
	if len(violations) > 0 {
		sort.Strings(violations)
		for _, v := range violations {
			t.Errorf("GUARD-V4: %s", v)
		}
		t.FailNow()
	}
}

// trackedTextFiles lists code-adjacent text files for marker scanning:
// BUILD_INPUT class (.go/.yaml/.yml/.json) plus CRD/docs contracts. README
// prose is included by public boundary policy: private schema names must not
// leak into public docs either (§9 classification recorded here).
func trackedTextFiles(t *testing.T, root string) []string {
	t.Helper()
	var out []string
	filepath.WalkDir(root, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		rel, rerr := filepath.Rel(root, p)
		if rerr != nil {
			return nil
		}
		rel = filepath.ToSlash(rel)
		if rel == "." {
			return nil
		}
		if d.IsDir() {
			switch d.Name() {
			case "vendor", ".git", "bin", "dist", "node_modules":
				return filepath.SkipDir
			}
			return nil
		}
		if d.Type()&os.ModeSymlink != 0 {
			return nil
		}
		for _, ext := range []string{".go", ".yaml", ".yml", ".json", ".md"} {
			if strings.HasSuffix(rel, ext) && !strings.HasSuffix(rel, "guard_v4_test.go") {
				out = append(out, rel)
			}
		}
		return nil
	})
	return out
}

func pinnedPrefix(pinned map[string]bool, imp string) string {
	best := ""
	for mod := range pinned {
		if (imp == mod || strings.HasPrefix(imp, mod+"/")) && len(mod) > len(best) {
			best = mod
		}
	}
	return best
}

func isStdlibV4(imp string) bool {
	first := imp
	if i := strings.Index(imp, "/"); i >= 0 {
		first = imp[:i]
	}
	return !strings.Contains(first, ".")
}
